apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/deployment.yml
- frontend/service.yml
- backend/deployment.yml
- backend/service.yml
- backend/hpa.yml
- ingress.yml

images:
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newTag: 991093af5a00294822e280383f74dab2d03b62fb
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newTag: 991093af5a00294822e280383f74dab2d03b62fb
